sonar.projectKey=Ozan-Gitar-POC_Customer-Pulse-oy
sonar.projectName=Customer Pulse
sonar.organization=ozan-gitar-poc

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests,frontend/tests
sonar.exclusions=**/node_modules/**,**/__pycache__/**,frontend/src/assets/**

sonar.python.version=3
sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.typescript.tsconfigPath=frontend/tsconfig.json
